/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gym.app.gymapp.frames;

import com.gym.app.gymapp.classes.Usuario;
import com.gym.app.gymapp.features.UsuarioDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class ClienteV1 extends javax.swing.JFrame {

    int xMouse, yMouse;
    public ClienteV1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        header1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdClient = new javax.swing.JTextField();
        txtAgeClient = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLastnameClient = new javax.swing.JTextField();
        txtPhoneClient = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtNameClient = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtMailClient = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        txtBuscarCliente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        header1.setBackground(new java.awt.Color(255, 255, 255));
        header1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                header1MouseDragged(evt);
            }
        });
        header1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                header1MousePressed(evt);
            }
        });

        btnVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Documents\\NetBeansProjects\\Gym-App\\src\\main\\resources\\volverr.png")); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salir.png"))); // NOI18N
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(15, 15, 15))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir)
                    .addComponent(btnVolver))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Apellido");

        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Edad");

        txtIdClient.setBackground(new java.awt.Color(255, 255, 255));
        txtIdClient.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIdClient.setForeground(new java.awt.Color(204, 204, 204));
        txtIdClient.setText("Ingrese el ID");
        txtIdClient.setBorder(null);
        txtIdClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIdClientMousePressed(evt);
            }
        });

        txtAgeClient.setBackground(new java.awt.Color(255, 255, 255));
        txtAgeClient.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtAgeClient.setForeground(new java.awt.Color(204, 204, 204));
        txtAgeClient.setText("Ingrese la edad");
        txtAgeClient.setBorder(null);
        txtAgeClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAgeClientMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Correo");

        txtLastnameClient.setBackground(new java.awt.Color(255, 255, 255));
        txtLastnameClient.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtLastnameClient.setForeground(new java.awt.Color(204, 204, 204));
        txtLastnameClient.setText("Ingrese el apellido");
        txtLastnameClient.setBorder(null);
        txtLastnameClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtLastnameClientMousePressed(evt);
            }
        });
        txtLastnameClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastnameClientActionPerformed(evt);
            }
        });

        txtPhoneClient.setBackground(new java.awt.Color(255, 255, 255));
        txtPhoneClient.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPhoneClient.setForeground(new java.awt.Color(204, 204, 204));
        txtPhoneClient.setText("Ingrese el telefono");
        txtPhoneClient.setBorder(null);
        txtPhoneClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPhoneClientMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Telefono");

        txtNameClient.setBackground(new java.awt.Color(255, 255, 255));
        txtNameClient.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNameClient.setForeground(new java.awt.Color(204, 204, 204));
        txtNameClient.setText("Ingrese el nombre");
        txtNameClient.setBorder(null);
        txtNameClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNameClientMousePressed(evt);
            }
        });
        txtNameClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameClientActionPerformed(evt);
            }
        });

        txtMailClient.setBackground(new java.awt.Color(255, 255, 255));
        txtMailClient.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtMailClient.setForeground(new java.awt.Color(204, 204, 204));
        txtMailClient.setText("Ingrese el correo");
        txtMailClient.setBorder(null);
        txtMailClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMailClientMousePressed(evt);
            }
        });
        txtMailClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailClientActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("ID");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar1.setText("Editar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        txtBuscarCliente.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscarCliente.setText("Buscar Cliente");
        txtBuscarCliente.setBorder(null);
        txtBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarClienteMousePressed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLastnameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAgeClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(bgLayout.createSequentialGroup()
                            .addComponent(btnGuardar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditar1)))
                    .addComponent(btnEliminar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator7)
                            .addComponent(txtBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscar)
                                    .addComponent(btnReset))))
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(txtNameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(txtLastnameClient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(txtAgeClient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(txtPhoneClient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(txtMailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnGuardar)
                                    .addComponent(btnEditar1))
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar1))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        Principal p = new Principal();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
        btnVolver.setBackground(Color.red);
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        btnVolver.setBackground(Color.white);
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnSalir.setBackground(Color.red);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        btnSalir.setBackground(Color.white);
    }//GEN-LAST:event_btnSalirMouseExited

    private void header1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_header1MouseDragged

    private void header1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_header1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_header1MousePressed

    private void txtIdClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdClientMousePressed
        if (txtIdClient.getText().equals("Ingrese el ID")) {
            txtIdClient.setText("");
            txtIdClient.setForeground(Color.black);
        }

        // Resetea los otros campos solo si no tienen datos personalizados
        if (txtNameClient.getText().isEmpty() || txtNameClient.getText().equals("Ingrese el nombre")) {
            txtNameClient.setText("Ingrese el nombre");
            txtNameClient.setForeground(Color.gray);
        }

        if (txtLastnameClient.getText().isEmpty() || txtLastnameClient.getText().equals("Ingrese el apellido")) {
            txtLastnameClient.setText("Ingrese el apellido");
            txtLastnameClient.setForeground(Color.gray);
        }

        if (txtAgeClient.getText().isEmpty() || txtAgeClient.getText().equals("Ingrese la edad")) {
            txtAgeClient.setText("Ingrese la edad");
            txtAgeClient.setForeground(Color.gray);
        }

        if (txtPhoneClient.getText().isEmpty() || txtPhoneClient.getText().equals("Ingrese el telefono")) {
            txtPhoneClient.setText("Ingrese el telefono");
            txtPhoneClient.setForeground(Color.gray);
        }

        if (txtMailClient.getText().isEmpty() || txtMailClient.getText().equals("Ingrese el correo")) {
            txtMailClient.setText("Ingrese el correo");
            txtMailClient.setForeground(Color.gray);
        }
        if (txtBuscarCliente.getText().isEmpty() || txtBuscarCliente.getText().equals("Buscar Cliente")) {
            txtBuscarCliente.setText("Buscar Cliente");
            txtBuscarCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtIdClientMousePressed

    private void txtAgeClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgeClientMousePressed
        if (txtIdClient.getText().isEmpty() || txtIdClient.getText().equals("Ingrese el ID")) {
            txtIdClient.setText("Ingrese el ID");
            txtIdClient.setForeground(Color.gray);
        }

        if (txtNameClient.getText().isEmpty() || txtNameClient.getText().equals("Ingrese el nombre")) {
            txtNameClient.setText("Ingrese el nombre");
            txtNameClient.setForeground(Color.gray);
        }

        if (txtLastnameClient.getText().isEmpty() || txtLastnameClient.getText().equals("Ingrese el apellido")) {
            txtLastnameClient.setText("Ingrese el apellido");
            txtLastnameClient.setForeground(Color.gray);
        }

        if (txtAgeClient.getText().equals("Ingrese la edad")) {
            txtAgeClient.setText("");
            txtAgeClient.setForeground(Color.BLACK);
        }

        if (txtPhoneClient.getText().isEmpty() || txtPhoneClient.getText().equals("Ingrese el telefono")) {
            txtPhoneClient.setText("Ingrese el telefono");
            txtPhoneClient.setForeground(Color.gray);
        }

        if (txtMailClient.getText().isEmpty() || txtMailClient.getText().equals("Ingrese el correo")) {
            txtMailClient.setText("Ingrese el correo");
            txtMailClient.setForeground(Color.gray);
        }
        if (txtBuscarCliente.getText().isEmpty() || txtBuscarCliente.getText().equals("Buscar Cliente")) {
            txtBuscarCliente.setText("Buscar Cliente");
            txtBuscarCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtAgeClientMousePressed

    private void txtLastnameClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLastnameClientMousePressed
        if (txtIdClient.getText().isEmpty() || txtIdClient.getText().equals("Ingrese el ID")) {
            txtIdClient.setText("Ingrese el ID");
            txtIdClient.setForeground(Color.gray);
        }

        if (txtNameClient.getText().isEmpty() || txtNameClient.getText().equals("Ingrese el nombre")) {
            txtNameClient.setText("Ingrese el nombre");
            txtNameClient.setForeground(Color.gray);
        }

        if (txtLastnameClient.getText().equals("Ingrese el apellido")) {
            txtLastnameClient.setText("");
            txtLastnameClient.setForeground(Color.BLACK);
        }

        if (txtAgeClient.getText().isEmpty() || txtAgeClient.getText().equals("Ingrese la edad")) {
            txtAgeClient.setText("Ingrese la edad");
            txtAgeClient.setForeground(Color.gray);
        }

        if (txtPhoneClient.getText().isEmpty() || txtPhoneClient.getText().equals("Ingrese el telefono")) {
            txtPhoneClient.setText("Ingrese el telefono");
            txtPhoneClient.setForeground(Color.gray);
        }

        if (txtMailClient.getText().isEmpty() || txtMailClient.getText().equals("Ingrese el correo")) {
            txtMailClient.setText("Ingrese el correo");
            txtMailClient.setForeground(Color.gray);
        }
        if (txtBuscarCliente.getText().isEmpty() || txtBuscarCliente.getText().equals("Buscar Cliente")) {
            txtBuscarCliente.setText("Buscar Cliente");
            txtBuscarCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtLastnameClientMousePressed

    private void txtLastnameClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastnameClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastnameClientActionPerformed

    private void txtPhoneClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPhoneClientMousePressed
        if (txtIdClient.getText().isEmpty() || txtIdClient.getText().equals("Ingrese el ID")) {
            txtIdClient.setText("Ingrese el ID");
            txtIdClient.setForeground(Color.gray);
        }

        if (txtNameClient.getText().isEmpty() || txtNameClient.getText().equals("Ingrese el nombre")) {
            txtNameClient.setText("Ingrese el nombre");
            txtNameClient.setForeground(Color.gray);
        }

        if (txtLastnameClient.getText().isEmpty() || txtLastnameClient.getText().equals("Ingrese el apellido")) {
            txtLastnameClient.setText("Ingrese el apellido");
            txtLastnameClient.setForeground(Color.gray);
        }

        if (txtAgeClient.getText().isEmpty() || txtAgeClient.getText().equals("Ingrese la edad")) {
            txtAgeClient.setText("Ingrese la edad");
            txtAgeClient.setForeground(Color.gray);
        }

        if (txtPhoneClient.getText().equals("Ingrese el telefono")) {
            txtPhoneClient.setText("");
            txtPhoneClient.setForeground(Color.BLACK);
        }

        if (txtMailClient.getText().isEmpty() || txtMailClient.getText().equals("Ingrese el correo")) {
            txtMailClient.setText("Ingrese el correo");
            txtMailClient.setForeground(Color.gray);
        }
        if (txtBuscarCliente.getText().isEmpty() || txtBuscarCliente.getText().equals("Buscar Cliente")) {
            txtBuscarCliente.setText("Buscar Cliente");
            txtBuscarCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtPhoneClientMousePressed

    private void txtNameClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameClientMousePressed
        if (txtIdClient.getText().isEmpty() || txtIdClient.getText().equals("Ingrese el ID")) {
            txtIdClient.setText("Ingrese el ID");
            txtIdClient.setForeground(Color.gray);
        }

        if (txtNameClient.getText().equals("Ingrese el nombre")) {
            txtNameClient.setText("");
            txtNameClient.setForeground(Color.BLACK);
        }

        if (txtLastnameClient.getText().isEmpty() || txtLastnameClient.getText().equals("Ingrese el apellido")) {
            txtLastnameClient.setText("Ingrese el apellido");
            txtLastnameClient.setForeground(Color.gray);
        }

        if (txtAgeClient.getText().isEmpty() || txtAgeClient.getText().equals("Ingrese la edad")) {
            txtAgeClient.setText("Ingrese la edad");
            txtAgeClient.setForeground(Color.gray);
        }

        if (txtPhoneClient.getText().isEmpty() || txtPhoneClient.getText().equals("Ingrese el telefono")) {
            txtPhoneClient.setText("Ingrese el telefono");
            txtPhoneClient.setForeground(Color.gray);
        }

        if (txtMailClient.getText().isEmpty() || txtMailClient.getText().equals("Ingrese el correo")) {
            txtMailClient.setText("Ingrese el correo");
            txtMailClient.setForeground(Color.gray);
        }
        if (txtBuscarCliente.getText().isEmpty() || txtBuscarCliente.getText().equals("Buscar Cliente")) {
            txtBuscarCliente.setText("Buscar Cliente");
            txtBuscarCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtNameClientMousePressed

    private void txtNameClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameClientActionPerformed

    private void txtMailClientMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMailClientMousePressed
        if (txtIdClient.getText().isEmpty() || txtIdClient.getText().equals("Ingrese el ID")) {
            txtIdClient.setText("Ingrese el ID");
            txtIdClient.setForeground(Color.gray);
        }

        if (txtNameClient.getText().isEmpty() || txtNameClient.getText().equals("Ingrese el nombre")) {
            txtNameClient.setText("Ingrese el nombre");
            txtNameClient.setForeground(Color.gray);
        }

        if (txtLastnameClient.getText().isEmpty() || txtLastnameClient.getText().equals("Ingrese el apellido")) {
            txtLastnameClient.setText("Ingrese el apellido");
            txtLastnameClient.setForeground(Color.gray);
        }

        if (txtAgeClient.getText().isEmpty() || txtAgeClient.getText().equals("Ingrese la edad")) {
            txtAgeClient.setText("Ingrese la edad");
            txtAgeClient.setForeground(Color.gray);
        }

        if (txtPhoneClient.getText().isEmpty() || txtPhoneClient.getText().equals("Ingrese el telefono")) {
            txtPhoneClient.setText("Ingrese el telefono");
            txtPhoneClient.setForeground(Color.gray);
        }

        if (txtMailClient.getText().equals("Ingrese el correo")) {
            txtMailClient.setText("");
            txtMailClient.setForeground(Color.BLACK);
        }
        if (txtBuscarCliente.getText().isEmpty() || txtBuscarCliente.getText().equals("Buscar Cliente")) {
            txtBuscarCliente.setText("Buscar Cliente");
            txtBuscarCliente.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtMailClientMousePressed

    private void txtMailClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailClientActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            // Obtener el valor del campo de búsqueda
            String buscar = txtBuscarCliente.getText().trim();

            // Verificar que el campo de búsqueda no esté vacío
            if (buscar.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor ingresa el nombre y apellido para la búsqueda.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Dividir el texto en nombre y apellido usando un espacio
            String[] partes = buscar.split(" ");
            if (partes.length != 2) {
                JOptionPane.showMessageDialog(this, "Por favor ingresa el nombre y apellido separados por un espacio.",
                    "Error de formato", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String nombreCliente = partes[0];
            String apellidoCliente = partes[1];

            // Crear una instancia del DAO para obtener los clientes
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            List<Usuario> listaClientes = usuarioDAO.buscarClientePorNombreApellido(nombreCliente, apellidoCliente);

            // Verificar si se encontraron clientes
            if (listaClientes.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron clientes con ese nombre y apellido.",
                    "Sin Resultados", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Cargar los resultados en la tabla
                cargarTablaClientes(listaClientes);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al realizar la búsqueda: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    
    private void cargarUsuario() {
        try {
            // Obtener lista de membresías desde la base de datos
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            List<Usuario> listaUsuarios = usuarioDAO.obtenerClientesTotales();

            // Crear modelo de tabla
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID Usuario");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido");
            modelo.addColumn("Edad");
            modelo.addColumn("Telefono");
            modelo.addColumn("Correo");

            // Agregar datos al modelo
            for (Usuario usuario : listaUsuarios) {
                modelo.addRow(new Object[]{
                    usuario.getId_Cliente(),
                    usuario.getNombre_Cliente(),
                    usuario.getApellido_Cliente(),
                    usuario.getEdad_Cliente(),
                    usuario.getNumero_Cliente(),
                    usuario.getCorreo_Cliente()

                });
            }

            // Asignar modelo a la tabla
            tblClientes.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar membresías: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        cargarUsuario();
        txtBuscarCliente.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    public void limpiar() {
        txtAgeClient.setText("");
        txtIdClient.setText("");
        txtLastnameClient.setText("");
        txtMailClient.setText("");
        txtNameClient.setText("");
        txtPhoneClient.setText("");
    }
    
    private void cargarTablaClientes(List<Usuario> listaClientes) {
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        modelo.setRowCount(0);  // Limpiar tabla antes de agregar nuevas filas

        for (Usuario usuario : listaClientes) {
            modelo.addRow(new Object[]{
                usuario.getId_Cliente(),
                usuario.getNombre_Cliente(),
                usuario.getApellido_Cliente(),
                usuario.getEdad_Cliente(),
                usuario.getNumero_Cliente(),
                usuario.getCorreo_Cliente()
            });
        }
    }
    
    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        int fila = tblClientes.getSelectedRow();
        if (fila >= 0) {
            btnGuardar.setEnabled(false);
            txtIdClient.setText(tblClientes.getValueAt(fila, 0).toString());
            txtNameClient.setText(tblClientes.getValueAt(fila, 1).toString());
            txtLastnameClient.setText(tblClientes.getValueAt(fila, 2).toString());
            txtAgeClient.setText(tblClientes.getValueAt(fila, 3).toString());
            txtPhoneClient.setText(tblClientes.getValueAt(fila, 4).toString());
            txtMailClient.setText(tblClientes.getValueAt(fila, 5).toString());
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void txtBuscarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarClienteMousePressed
        if (txtBuscarCliente.getText().equals("Buscar Cliente")) {
            txtBuscarCliente.setText("");
            txtBuscarCliente.setForeground(Color.black);
        }

        // Resetea los otros campos solo si no tienen datos personalizados
        if (txtNameClient.getText().isEmpty() || txtNameClient.getText().equals("Ingrese el nombre")) {
            txtNameClient.setText("Ingrese el nombre");
            txtNameClient.setForeground(Color.gray);
        }

        if (txtLastnameClient.getText().isEmpty() || txtLastnameClient.getText().equals("Ingrese el apellido")) {
            txtLastnameClient.setText("Ingrese el apellido");
            txtLastnameClient.setForeground(Color.gray);
        }

        if (txtAgeClient.getText().isEmpty() || txtAgeClient.getText().equals("Ingrese la edad")) {
            txtAgeClient.setText("Ingrese la edad");
            txtAgeClient.setForeground(Color.gray);
        }

        if (txtPhoneClient.getText().isEmpty() || txtPhoneClient.getText().equals("Ingrese el telefono")) {
            txtPhoneClient.setText("Ingrese el telefono");
            txtPhoneClient.setForeground(Color.gray);
        }

        if (txtMailClient.getText().isEmpty() || txtMailClient.getText().equals("Ingrese el correo")) {
            txtMailClient.setText("Ingrese el correo");
            txtMailClient.setForeground(Color.gray);
        }
        if (txtIdClient.getText().isEmpty() || txtIdClient.getText().equals("Ingrese el ID")) {
            txtIdClient.setText("Ingrese el ID");
            txtIdClient.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtBuscarClienteMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteV1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JPanel header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtAgeClient;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtIdClient;
    private javax.swing.JTextField txtLastnameClient;
    private javax.swing.JTextField txtMailClient;
    private javax.swing.JTextField txtNameClient;
    private javax.swing.JTextField txtPhoneClient;
    // End of variables declaration//GEN-END:variables
}
